backend:
  name: github
  repo: owen8877/test2
  base_url: https://sveltia-cms-auth.xdroid.workers.dev/
  automatic_deployments: false

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
